### ISSUE TITLE
Add mutt

### ISSUE THREAD

**Issue by isfttr** [isetfiretotherain/ArchLabs_on_MacBook#3]
I'm trying to set up `mutt` to properly run but currently having problems with `offlineimap` so it is not syncing. If your are not going to use mutt, than you should try `mailspring` that has a nice gui and works fine with gmail.

**Comment by isfttr** [comment]
I'm putting this on hold for a while. Offlineimap keeps on running with failures of authentication and I simply can't keep wasting my time on this. 

Last errors were:

```
 XOAUTH2 authentication failed: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
 ERROR: All authentication types failed:
        XOAUTH2: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
 ['  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 283, in syncrunner\n    self.__sync()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 359, in __sync\n    remoterepos.getfolders()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 452, in getfolders\n    imapobj = self.imapserver.acquireconnection()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 586, in acquireconnection\n    self.__authn_helper(imapobj)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 459, in __authn_helper\n    "failed:\\n\\t%s"% msg, OfflineImapError.ERROR.REPO)\n']
 *** Finished account 'lucasfernandesdfgmail' in 0:01
 ERROR: Exceptions occurred during the run!
 ERROR: All authentication types failed:
        XOAUTH2: [AUTHENTICATIONFAILED] Invalid credentials (Failure)

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 283, in syncrunner
    self.__sync()
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 359, in __sync
    remoterepos.getfolders()
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 452, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 586, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 459, in __authn_helper
    "failed:\n\t%s"% msg, OfflineImapError.ERROR.REPO)

```

Reference from related issues:
https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L886-L894
https://github.com/OfflineIMAP/offlineimap/issues/573
https://github.com/OfflineIMAP/offlineimap/issues/228

**Comment by isfttr** [comment]
It is currently working, downloading emails. It cannot send emails, may need to configure smtp.

**Comment by isetfiretotherain** [comment]
Finally a solution has been reached using the [lukesmithxyz/mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard). It just worked out of the box. For gmail accounts it is needed to go the google account and enable access for third party apps.

**Comment by isfttr** [comment]
Finally a solution has been reached using the [lukesmithxyz/mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard). It just worked out of the box. For gmail accounts it is needed to go the google account and enable access for third party apps.
